# Generated by Django 3.2.4 on 2022-11-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('projectname', models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称')),
                ('casenum', models.CharField(help_text='用例数', max_length=200, verbose_name='用例数')),
                ('bugnum', models.CharField(help_text='bug数', max_length=200, verbose_name='bug数')),
                ('autotestnum', models.CharField(help_text='自动化数目', max_length=200, verbose_name='自动化数目')),
            ],
            options={
                'verbose_name': '项目名称',
                'verbose_name_plural': '项目名称',
                'db_table': 'td_pjname',
            },
        ),
    ]
