# Generated by Django 3.2.4 on 2021-07-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondLevelMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('authname', models.CharField(help_text='一级菜单', max_length=10, verbose_name='一级菜单')),
                ('path', models.CharField(help_text='一级菜单路径', max_length=10, verbose_name='一级菜单路径')),
            ],
            options={
                'verbose_name': '二级级菜单',
                'verbose_name_plural': '二级菜单',
                'db_table': 'td_secondmenu',
            },
        ),
    ]
