# Generated by Django 3.2.4 on 2021-07-13 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menutwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level1Model',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='一级菜单id')),
                ('authname', models.CharField(help_text='一级菜单名称', max_length=15, verbose_name='一级菜单名称')),
                ('path', models.CharField(help_text='一级菜单路径', max_length=15, verbose_name='一级菜单路径')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单',
                'db_table': 'td_menu_lv1',
            },
        ),
        migrations.CreateModel(
            name='Level2Model',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='二级菜单id')),
                ('authname', models.CharField(help_text='二级菜单名称', max_length=15, verbose_name='二级菜单名称')),
                ('path', models.CharField(help_text='二级菜单路径', max_length=15, verbose_name='二级菜单路径')),
                ('lv1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menutwo.level1model', verbose_name='一级菜单id外键')),
            ],
            options={
                'verbose_name': '二级菜单',
                'verbose_name_plural': '二级菜单',
                'db_table': 'td_menu_lv2',
            },
        ),
        migrations.DeleteModel(
            name='SecondLevelMenu',
        ),
    ]
