# Generated by Django 3.2.4 on 2021-07-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menutwo', '0002_auto_20210713_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level2model',
            old_name='lv1_id',
            new_name='level1',
        ),
    ]
