# Generated by Django 3.2.4 on 2021-07-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menutwo', '0003_rename_lv1_id_level2model_level1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level2model',
            name='level1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menutwo.level1model', verbose_name='一级菜单id外键'),
        ),
    ]
