# Generated by Django 3.2.4 on 2021-07-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('addrname', models.CharField(help_text='测试地址名称', max_length=10, verbose_name='测试地址名称')),
                ('uataddr', models.CharField(help_text='uat地址url', max_length=50, verbose_name='uat地址url')),
                ('prodaddr', models.CharField(help_text='prod地址url', max_length=50, verbose_name='prod地址url')),
            ],
            options={
                'verbose_name': '测试地址',
                'verbose_name_plural': '测试地址',
                'db_table': 'td_addr',
            },
        ),
    ]
