# Generated by Django 3.2.4 on 2021-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testaddress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testadressmodel',
            name='prodaddr',
            field=models.CharField(help_text='prod地址url', max_length=200, verbose_name='prod地址url'),
        ),
        migrations.AlterField(
            model_name='testadressmodel',
            name='uataddr',
            field=models.CharField(help_text='uat地址url', max_length=200, verbose_name='uat地址url'),
        ),
    ]
