# Generated by Django 3.2.4 on 2021-07-09 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menutwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelMenu',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('id', models.AutoField(help_text='id主键', primary_key=True, serialize=False, verbose_name='id主键')),
                ('authname', models.CharField(help_text='一级菜单', max_length=10, verbose_name='一级菜单')),
                ('path', models.CharField(help_text='一级菜单路径', max_length=10, verbose_name='一级菜单路径')),
                ('children', models.OneToOneField(help_text='对应二级菜单', on_delete=django.db.models.deletion.CASCADE, to='menutwo.secondlevelmenu')),
            ],
            options={
                'verbose_name': '一级菜单',
                'verbose_name_plural': '一级菜单',
                'db_table': 'td_firstmenu',
            },
        ),
    ]
