# Generated by Django 3.2.4 on 2021-07-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstlevelmenu',
            name='children',
        ),
    ]
