# Generated by Django 3.2.4 on 2021-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_firstlevelmenu_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlevelmenu',
            name='authname',
            field=models.CharField(help_text='一级菜单', max_length=10, verbose_name='一级菜单名称'),
        ),
    ]
